require: rubocop-rails

Metrics/LineLength:
  Max: 130
  Exclude:
    - 'spec/**/*'

Documentation:
  Enabled: false

NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'ActiveAdmin.register']
  Exclude:

Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'app/uploaders/**/*'
    - 'app/forms/address_form.rb'

Style/UnneededInterpolation:
  Exclude:
    - 'app/views/orders/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'app/decorators/book_decorator.rb'

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
